# Generated by Django 3.1.2 on 2021-02-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210206_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
