# Generated by Django 3.1.2 on 2021-02-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210206_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=10000)),
                ('time_stamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
