# Generated by Django 3.1.2 on 2021-02-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.RenameField(
            model_name='order_update',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order_update',
            name='update_desc',
            field=models.CharField(max_length=5000),
        ),
    ]
