# Generated by Django 3.1.2 on 2021-02-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210208_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_update',
            new_name='OrderUpdate',
        ),
    ]
